version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - mynetwork

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testflask
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  
networks:
  mynetwork: